development:
  adapter: mysql2
  encoding: utf8
  database: DesignaDefault_development
  username: root
  password:
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: DesignaDefault_test
  username: root
  password:
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: shibatacasa
  username: root
  password:
  host: localhost
  port: 3306
