development:
  adapter: mysql2
  encoding: utf8
  database: querolegenda_development
  username: root
  password:
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: querolegenda_test
  username: root
  password:
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: querolegenda
  username: root
  password:
  host: localhost
  port: 3306
